# Site settings
title: "Ion"
description: "High-performance concurrency primitives for Go applications. Rate limiting, semaphores, and worker pools designed for production workloads."
baseurl: "/ion"
url: "https://kolosys.com"

# Repository
repository: "kolosys/ion"

# Theme - Using Kolosys Docs Theme
remote_theme: kolosys/.github-theme
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Navigation structure for Ion
nav_sections:
  - title: "Getting Started"
    items:
      - title: "Introduction"
        url: /
      - title: "Installation"
        url: /getting-started/
      - title: "Quick Start"
        url: /getting-started/#quick-start

  - title: "Components"
    items:
      - title: "Rate Limiting"
        url: /components/#rate-limiting
        children:
          - title: "Token Bucket"
            url: /ratelimit/tokenbucket/
          - title: "Leaky Bucket"
            url: /ratelimit/leakybucket/
      - title: "Semaphores"
        url: /components/#semaphores
        children:
          - title: "Weighted Semaphore"
            url: /semaphore/weighted/
      - title: "Worker Pools"
        url: /components/#worker-pools
        children:
          - title: "Pool Management"
            url: /workerpool/pool/
          - title: "Task Submission"
            url: /workerpool/submit/

  - title: "Reference"
    items:
      - title: "API Reference"
        url: /api-reference/
      - title: "Examples"
        url: /examples/
      - title: "Benchmarks"
        url: /benchmarks/
      - title: "Contributing"
        url: /contributing/

# Collections
collections:
  components:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "components"
    values:
      layout: "component"

# Branding
logo: /assets/images/kolosys-ion.png
github_username: kolosys
twitter_username: kolosys

# Hero section
hero_buttons:
  - text: "Get Started →"
    url: "/getting-started/"
    type: "primary"
  - text: "View on GitHub"
    url: "https://github.com/kolosys/ion"
    type: "outline"
  - text: "API Docs"
    url: "/api-reference/"
    type: "secondary"

# Features for Ion
features:
  - title: "🚀 Rate Limiting"
    description: "Token bucket and leaky bucket algorithms for controlling request rates with configurable burst handling."
    link: /components/#rate-limiting

  - title: "🔒 Semaphores"
    description: "Weighted semaphores for resource management and access control with context-aware acquisition."
    link: /components/#semaphores

  - title: "⚡ Worker Pools"
    description: "Efficient worker pool implementation for concurrent task processing with graceful shutdown."
    link: /components/#worker-pools

  - title: "🎯 Context-Aware"
    description: "All components respect Go's context cancellation patterns for graceful shutdown and timeouts."
    link: /getting-started/#context-usage

  - title: "📦 Zero Dependencies"
    description: "Built using only Go's standard library with no external dependencies for maximum compatibility."
    link: /getting-started/#installation

  - title: "✅ Production Ready"
    description: "Battle-tested in production environments with comprehensive testing and benchmarks."
    link: /benchmarks/

# Footer
footer_links:
  - title: "Documentation"
    url: "/"
  - title: "GitHub"
    url: "https://github.com/kolosys/ion"
    external: true
  - title: "Issues"
    url: "https://github.com/kolosys/ion/issues"
    external: true
  - title: "Benchmarks"
    url: "/benchmarks/"

# SEO
social:
  name: Kolosys
  links:
    - https://github.com/kolosys

# Theme settings
show_sidebar: true
show_edit_link: true

# Custom copyright
copyright: "© 2024 Kolosys. All rights reserved."

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
