name: Continuous Integration
on:
  push:
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: kolosys/.actions/.github/workflows/ci-workflow.yml@main
    with:
      go_version: "1.22"
